server:
    port: 9100

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sso-chat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

sso:
    authUrl: http://localhost:9000/api/auth?token=%s
